#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop.

min=1
hus=0
while [ $hus -le 12 ]
do
    echo "Hour: $hus"
    while [ $min -le 59 ]
    do
        echo $min
        min=$(( min + 1 ))
    done
    min=1
    hus=$(( hus + 1))
done